name: tajiryol
description: ecommerce cross-platform app
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

  # state and network
  get: ^4.0.0-nullsafety.2
  provider: ^5.0.0
  dio: ^3.0.10 #dio: ^4.0.0-prev3
  json_annotation: ^3.1.1
  meta: ^1.3.0 
  equatable: ^2.0.0
  
  #UI
  # flutter_splash_screen: ^0.1.0
  pull_to_refresh: ^1.6.4
  flutter_screenutil: ^5.0.0-nullsafety.11
  modal_bottom_sheet: ^2.0.0
  dropdown_search: ^0.5.0
  flutter_svg: ^0.21.0-nullsafety.0 #nnbd - ^0.20.0-nullsafety.3
  shared_preferences: ^2.0.5 #^2.0.3
  flutter_swiper: ^1.1.6
  cached_network_image: ^2.5.1 #cached_network_image: ^3.0.0-nullsafety
  sticky_headers: ^0.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.1
  json_serializable: ^3.5.1 #json_serializable: ^4.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat/Montserrat-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald/Oswald-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Oswald/Oswald-Light.ttf
          weight: 300
        - asset: assets/fonts/Oswald/Oswald-Regular.ttf
          weight: 400
        - asset: assets/fonts/Oswald/Oswald-Medium.ttf
          weight: 500
        - asset: assets/fonts/Oswald/Oswald-SemiBold.ttf
          weight: 600          
        - asset: assets/fonts/Oswald/Oswald-Bold.ttf
          weight: 700

  