name: tajiryol
description: ecommerce cross-platform app
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # state and network
  get: ^3.26.0
  provider: ^5.0.0
  dio: ^3.0.10
  json_annotation: ^4.0.0-nullsafety.0
  meta: '>=1.0.0 <2.0.0' #artemis: only if you have non nullable fields
  equatable: ^2.0.0
  
  #UI
  flutter_splash_screen: ^0.1.0
  pull_to_refresh: ^1.6.4
  flutter_screenutil: ^4.0.4
  modal_bottom_sheet: ^2.0.0
  dropdown_search: ^0.4.8
  flutter_svg: #nnbd - ^0.20.0-nullsafety.3
  shared_preferences: #^2.0.3
  flutter_swiper: ^1.1.6
  cached_network_image: ^2.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.1
  json_serializable: ^4.0.0-nullsafety.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
  